import React, { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import styles from './BriefViewer.module.css'

const TABS = [
  { id: 'brief', label: 'Legal Brief' },
  { id: 'summary', label: 'Plain Summary' },
  { id: 'eligibility', label: 'Eligibility' },
  { id: 'rights', label: 'Rights' },
  { id: 'critic', label: 'Review' },
  { id: 'sources', label: 'Sources' },
]

export default function BriefViewer({ result }) {
  const [tab, setTab] = useState('brief')
  const retrievedSources = Array.isArray(result.retrieved_sources) ? result.retrieved_sources : []
  const revisionHistory = Array.isArray(result.revision_history) ? result.revision_history : []

  const content = {
    brief: result.final_brief,
    summary: result.plain_summary,
    eligibility: result.eligibility_report,
    rights: result.rights_report,
    critic: result.critic_feedback,
  }
  const criticApproved = (result.critic_verdict || '').toUpperCase() === 'APPROVE'

  const handlePrint = () => {
    const win = window.open('', '_blank')
    if (!win) return

    win.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Legal Brief - ${result.case_id}</title>
        <style>
          body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #111; }
          h1, h2, h3, h4 { font-family: Georgia, serif; }
          hr { border: 1px solid #ccc; margin: 1.5rem 0; }
          .footer { margin-top: 2rem; font-size: 0.75rem; color: #999; border-top: 1px solid #eee; padding-top: 1rem; }
        </style>
      </head>
      <body>
        ${result.final_brief.replace(/\n/g, '<br>')}
        <div class="footer">Generated by Undertrial Intelligence System - Case ID: ${result.case_id} - Revisions: ${result.revisions_done}</div>
      </body>
      </html>
    `)
    win.document.close()
    win.print()
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(content[tab] || '')
  }

  return (
    <div className={styles.wrap}>
      <div className={styles.topBar}>
        <div className={styles.caseInfo}>
          <span className={styles.caseId}>{result.case_id}</span>
          <div className={styles.meta}>
            <span className={styles.metaBadge}>
              {result.revisions_done} revision{result.revisions_done !== 1 ? 's' : ''}
            </span>
            <span className={`${styles.metaBadge} ${criticApproved ? styles.success : styles.warning}`}>
              {criticApproved ? 'Critic approved' : (result.critic_verdict || 'Review pending')}
            </span>
            {retrievedSources.length > 0 && (
              <span className={styles.metaBadge}>
                {retrievedSources.length} source{retrievedSources.length !== 1 ? 's' : ''}
              </span>
            )}
          </div>
        </div>
        <div className={styles.actions}>
          <button className={styles.actionBtn} onClick={handleCopy} title="Copy current tab">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
            </svg>
            Copy
          </button>
          <button className={styles.actionBtn} onClick={handlePrint} title="Print brief">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
              <polyline points="6 9 6 2 18 2 18 9" />
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
              <rect x="6" y="14" width="12" height="8" />
            </svg>
            Print
          </button>
        </div>
      </div>

      <div className={styles.tabs}>
        {TABS.map((tabItem) => (
          <button
            key={tabItem.id}
            className={`${styles.tab} ${tab === tabItem.id ? styles.tabActive : ''}`}
            onClick={() => setTab(tabItem.id)}
          >
            {tabItem.label}
          </button>
        ))}
      </div>

      <div className={styles.content}>
        {tab === 'summary' ? (
          <div className={styles.summaryCard}>
            <div className={styles.summaryHeader}>
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
              </svg>
              Plain-language summary for the accused's family
            </div>
            <div className={`prose ${styles.summaryProse}`}>
              <ReactMarkdown>{result.plain_summary}</ReactMarkdown>
            </div>
          </div>
        ) : tab === 'sources' ? (
          <SourcesPanel result={result} />
        ) : (
          <div className={`prose ${styles.briefProse}`}>
            <ReactMarkdown>{content[tab] || '*No content available.*'}</ReactMarkdown>
          </div>
        )}
      </div>

      <div className={styles.footer}>
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        Generated by Undertrial Intelligence System. To be reviewed and endorsed by a qualified advocate before filing in court.
      </div>
    </div>
  )
}

function SourcesPanel({ result }) {
  const allSources = Array.isArray(result.retrieved_sources) ? result.retrieved_sources : []
  const revisionHistory = Array.isArray(result.revision_history) ? result.revision_history : []
  const groupedSources = [
    ['Eligibility', allSources.filter((source) => source.used_by?.includes('eligibility'))],
    ['Rights', allSources.filter((source) => source.used_by?.includes('rights'))],
    ['Shared', allSources.filter((source) => (source.used_by || []).length > 1)],
  ]

  return (
    <div className={styles.sourcesPanel}>
      <div className={styles.sourcesIntro}>
        <div>
          <h3 className={styles.sourcesTitle}>Authorities reviewed</h3>
          <p className={styles.sourcesDesc}>
            These excerpts were retrieved from the knowledge base and used to ground the reports.
          </p>
        </div>
        <div className={styles.reviewMeta}>
          <div className={styles.reviewMetaRow}>
            <span>Critic verdict</span>
            <strong>{result.critic_verdict || 'Not available'}</strong>
          </div>
          <div className={styles.reviewMetaRow}>
            <span>Revision count</span>
            <strong>{result.revisions_done || 0}</strong>
          </div>
        </div>
      </div>

      {revisionHistory.length > 0 && (
        <div className={styles.historyPanel}>
          <div className={styles.historyTitle}>Revision history</div>
          <div className={styles.historyList}>
            {revisionHistory.map((entry, index) => (
              <div key={`${entry.iteration}-${index}`} className={styles.historyItem}>
                <div className={styles.historyHeader}>
                  <span>Pass {entry.iteration}</span>
                  <span className={`${styles.historyVerdict} ${entry.verdict === 'APPROVE' ? styles.successText : styles.warningText}`}>
                    {entry.verdict}
                  </span>
                </div>
                {entry.issues?.length > 0 ? (
                  <ul className={styles.historyIssues}>
                    {entry.issues.map((issue) => <li key={issue}>{issue}</li>)}
                  </ul>
                ) : (
                  <div className={styles.historyClean}>No issues recorded.</div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      <div className={styles.sourceGroups}>
        {groupedSources.map(([label, sources]) => (
          <section key={label} className={styles.sourceSection}>
            <div className={styles.sourceSectionHeader}>
              <h4>{label} authorities</h4>
              <span>{sources.length}</span>
            </div>
            {sources.length > 0 ? (
              <div className={styles.sourceList}>
                {sources.map((source, index) => (
                  <article key={`${source.document_id || source.title}-${index}`} className={styles.sourceCard}>
                    <div className={styles.sourceCardTop}>
                      <div>
                        <div className={styles.sourceTitle}>{source.title || 'Untitled source'}</div>
                        <div className={styles.sourceMeta}>
                          {[source.source, source.category, source.court, source.document_id].filter(Boolean).join(' • ')}
                        </div>
                      </div>
                      <div className={styles.sourceTags}>
                        {(source.used_by || []).map((tag) => (
                          <span key={tag} className={styles.sourceTag}>{tag}</span>
                        ))}
                      </div>
                    </div>
                    <p className={styles.sourceExcerpt}>{source.excerpt || 'No excerpt available.'}</p>
                  </article>
                ))}
              </div>
            ) : (
              <div className={styles.sourceEmpty}>No authorities captured for this analysis stream.</div>
            )}
          </section>
        ))}
      </div>
    </div>
  )
}
